blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('front.urls'))
]

front/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.index, name='index'),
	path('make/', views.MakeView.as_view(), name='make_list'),
	path('make/create/', views.MakeCreate.as_view(), name='make_create'),
	path('make/<int:pk>/update', views.MakeUpdate.as_view(), name='make_update'),
	path('make/<int:pk>/delete', views.MakeDelete.as_view(), name='make_delete'),
	path('car/create/', views.CarCreate.as_view(), name='car_create'),
	path('cars/', views.CarView.as_view(), name='car_list'),
	path('car/<int:pk>/update', views.CarUpdate.as_view(), name='car_update'),
	path('car/<int:pk>/delete', views.CarDelete.as_view(), name='car_delete'), 
]

front/models.py
from django.db import models
from django.core.validators import MinLengthValidator


class Make(models.Model):
    name = models.CharField(
            max_length=200, 
            help_text='Enter a make (e.g. Dodge)',
            validators=[MinLengthValidator(2, "Make must be greater than 1 character")]
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Auto(models.Model):
    nombre = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    km = models.PositiveIntegerField()
    comments = models.CharField(max_length=300)
    brand = models.CharField(max_length=300)

    # Shows up in the admin list
    def __str__(self):
        return self.nombre

front/forms.py
from django.forms import ModelForm, ModelChoiceField
from front.models import Auto, Make


# Create the form class.
class MakeForm(ModelForm):
    class Meta:
        model = Make
        fields = '__all__'


# class CarcreateForm2(ModelForm):
    
#     brands = ModelChoiceField(queryset=Make.objects.none())

#     def __init__(self, *args, **kwargs):
#         self.my_var = kwargs.pop('my_var2')
#         super(CarcreateForm, self).__init__(*args, **kwargs)
#         self.fields['brand'].queryset = Make.objects.filter(type=self.my_var)

#     class Meta:
#         model = Auto
#         fields = '__all__'


class CarcreateForm(ModelForm):

	brand = ModelChoiceField(queryset=Make.objects.none())
	

	def __init__(self, *args, **kwargs):
		print(kwargs)
		# print(kwargs["instance"].id)
		# ModelChoiceField(queryset=Make.objects.filter(id=kwargs["instance"].id))
		
		if 'brand' in kwargs:
			self.brand = kwargs.pop('brand')
		super(CarcreateForm, self).__init__(*args, **kwargs)
		#self.initial['brand'] = 'ford'
		#self.fields['brand'].queryset = Make.objects.filter(type=self.my_var)
		#self.fields['brand'].queryset = Make.objects.filter(id=kwargs["instance"].id)
		self.fields['brand'].queryset = Make.objects.all()
		#self.fields['brand'] = ModelChoiceField(queryset=Make.objects.all(), empty_label="(Nothing)", initial={'id': 2})

	class Meta:
		model = Auto
		fields = '__all__'

front/views.py
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from front.models import Auto, Make
from django.urls import reverse_lazy
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404

from front.forms import CarcreateForm


def index(request):
    #return HttpResponse("Hello, world. You're at the front index.")
	context={"test":"test"}
	return render(request, 'front/index.html', context)



class MakeView(View):
    def get(self, request):
        ml = Make.objects.all()
        ctx = {'make_list': ml}
        return render(request, 'front/make_list.html', ctx)



class CarView(View):
	def get(self, request):
		bc = Make.objects.count()
		ml = Auto.objects.all()
		ctx = {'car_list': ml, 'brand_count':bc}
		return render(request, 'front/car_list.html', ctx)


class MakeCreate(CreateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('make_list')

class MakeUpdate(UpdateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('index')

class MakeDelete(DeleteView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('make_list') 


# class CarCreate(CreateView):
# 	model = Auto
# 	fields = '__all__'

# 	#brand = ModelChoiceField(queryset=Make.objects.none())

# 	def __init__(self, *args, **kwargs):
# 		#self.my_var = kwargs.pop('my_var2')
# 		#super(self).__init__(*args, **kwargs)
# 		#self.fields['brand'].queryset = Make.objects.filter(type=self.my_var)
# 		self.fields['brand'].queryset = Make.objects.all()

# 	def form_valid(self, form):
# 		return super(CarCreate, self).form_valid(form)

# 	def get_context_data(self, **kwargs):
# 		"""Insert the form into the context dict."""
# 		print(self.get_form())
# 		if 'form' not in kwargs:
# 			form = self.get_form()
# 			#form= form.replace('brand', 'brand2')
# 			kwargs['form'] = form
# 		print(kwargs)
# 		return super().get_context_data(**kwargs)

# 	# def get_form_kwargs(self):
# 	# 	kwargs = super(CarCreate, self).get_form_kwargs()
# 	# 	kwargs.update({'my_var2': 'my value'})
# 	# 	return kwargs	
	
	
# 	success_url = reverse_lazy('car_list')


class CarCreate(View):
	template = 'front/make_form.html'
	success_url = reverse_lazy('index')

	def get(self, request):
		form = CarcreateForm()
		print(form)
		ctx = {'form': form}
		return render(request, self.template, ctx)

	def post(self, request):
		form = CarcreateForm(request.POST)
		if not form.is_valid():
			ctx = {'form': form}
			return render(request, self.template, ctx)

		make = form.save()
		return redirect(self.success_url)


class CarUpdate(View):
	model = Auto
	template = 'front/auto_form.html'
	success_url = reverse_lazy('car_list')

	def get(self, request, pk):
		car = get_object_or_404(self.model, pk=pk)
		form = CarcreateForm(instance=car,brand='')
		#form.fields['brand'].queryset = Make.objects.filter(id=pk)
		print(car.brand)
		ctx = {'form': form, 'brand': car.brand}
		return render(request, self.template, ctx)

	def post(self, request, pk):
		car = get_object_or_404(self.model, pk=pk)
		form = CarcreateForm(request.POST, instance=car)
		if not form.is_valid():
			ctx = {'form': form}
			return render(request, self.template, ctx)

		Auto = form.save()
		return redirect(self.success_url)


class CarDelete(View):
    model = Auto
    success_url = reverse_lazy('car_list')
    template = 'front/car_confirm_delete.html'

    def get(self, request, pk):
        car = get_object_or_404(self.model, pk=pk)
        form = CarcreateForm(instance=car)
        ctx = {'car': car}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        car = get_object_or_404(self.model, pk=pk)
        car.delete()
        return redirect(self.success_url)


	
# class CarDelete(View):
# 	def get(self, request):
# 		return 'ok'

front/templates/base.html
<!DOCTYPE html>
<html>
<head>

<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>


<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

{% block head %} {% endblock %}




</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
{% block js %}
{% endblock %}
</body>
</html>

front/templates/front/auto_form.html
{% extends "base.html" %}

{% block js %}
<script>
  $('select option:contains("{{ brand }}")').attr('selected', true);
  //$("#id_brand").val('2');
</script>
{% endblock %}

{% block content %}


<h1>Add new car</h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'index' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

front/templates/front/car_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Car</h1>

<p>Are you sure you want to delete the Car: {{ car.nombre }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

front/templates/front/car_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Car List</h1>
  {% if car_list %}
  <ul>
    {% for car in car_list %}
      <li>
          {{ car.nombre }} ({{ car.brand }})
          (<a href="{% url 'car_update' car.id %}">Update</a> |
          <a href="{% url 'car_delete' car.id %}">Delete</a>) <br/>
          {{ car.comments }} ({{ car.km }} km)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no cars in the library.</p>
  {% endif %}
  <p>
    {% if brand_count > 0 %}
      <a href="{% url 'car_create' %}">Add an car</a>
    {% else %}
      Please add a Brand before you add an car.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'make_list' %}">View brands</a> ({{ brand_count }}) | 
    <a href="{% url 'make_create' %}">Add a brand</a>
  </p>
{% endblock %}

front/templates/front/index.html
{% extends "base.html" %}


{% block content %}

	<h1>We can go to:</h1><br>

	<a href="/make/">Create a new car's brand</a>
{% endblock %}

front/templates/front/make_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Brand</h1>

<p>Are you sure you want to delete the brand: {{ make }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'make_list' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

front/templates/front/make_form.html
{% extends "base.html" %}

{% block content %}
<br>
<h1>Add new brand</h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'index' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

front/templates/front/make_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Brands List</h1>
  {% if make_list %}
  <ul>
    {% for make in make_list %}
      <li>
          {{ make.name }}
         (<a href="{% url 'make_update' make.id %}">Update</a> |
          <a href="{% url 'make_delete' make.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no brands in the library.</p>
  {% endif %}
  <p><a href="{% url 'make_create' %}">Add a Brand</a></p>
  <p>
    <a href="{% url 'car_list' %}">Back to cars</a>
  </p>
{% endblock %}